version: 0

train: True
test: True
dataset_class_debug: False
debug: False
test_debug: False
device: "cuda"
test_parameters:
  save_test_outputs: False
trainer:
  num_epochs: 150
  resume_training: False
  checkpoint_path: "/home/psrahul/MasterThesis/repo/Phase3/CLIPandDetect/trained_models/13092022_2013/model.pth"
  val_save_interval: 50
  bbox_heatmap_loss: False
  bbox_scatter_loss: True
  bbox_giou_loss: False
  embedding_loss_start_epoch: -1
  bbox_loss_start_epoch: -1

data:
  train_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  val_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  test_data_root: "/home/psrahul/MasterThesis/datasets/PASCAL_2012_ZETA/base_classes/train/coco/"
  train_aug: False
  train_batch_size: 3
  val_batch_size: 3
  test_batch_size: 3
  input_dimension: 320 # EfficientNetB2
  #   input_dimension: 384  ResNet18
heatmap:
  output_dimension: 320
  radius_scaling: 16
  fix_radius: True
  fix_radius_value: 5
max_objects_per_image: 1
smp:
  model: "DeepLabV3Plus" #Unet" #"Unet" #DeepLabV3Plus"
  encoder_name: "mobilenet_v2" #"resnet50" #mobilenet_v2"
  encoder_weights: "imagenet" #"imagenet" #"swsl" #imagenet"
  decoder_output_classes: 16 #256 #16
  decoder_output_dimension: 320
  freeze_encoder: False

model:
  loss_weight:
    heatmap_head: 10
    bbox_head: 1
    offset_head: 0
    embedding_head: 1
logging:
  checkpoint_dir: "outputs/training_debug/"
  display_log_fraction: 1
evaluation:
  heatmap_pooling_kernel: 3
  topk_k: 1